---
title: "Cleo_gambling_trends"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages

```{r}
rm(list=ls()) #clear env
library(lme4)
library(lattice)
library(lmerTest)
library(emmeans)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(influence.ME)
library(gmodels)#CI
library(corrplot)
library(arm)
library(gridExtra)
library(sjPlot)
library(stringr)
library(httr)
#library(OSF2R)
library(osfr)
library(naniar)
library(QuantPsyc) #lm.beta() for standardized betas
library(AER)
library(mclogit)
library(nnet)


```

Read in Qualtrics data

```{r}

df <- read.csv("C:/Users/lsbcherkasovalab/Documents/Celo/Cleo_January 17, 2022_14.40.csv") #BE SURE TO EXPORT WITH 'USE NUMERIC VALUES'

```

Filter data
 
```{r}
qualtrics <- df %>% 
  filter(Q142=="" & Q141=="2") %>% #attention checks; if the data are exported form Qualtrics using text, a problem can occur at this point 
  dplyr::select(!c(cleo_data, cleo_ui))

```

Calculate gambling frequency scores, PGSI

```{r}

qualtrics[,39:179] <- sapply(qualtrics[,39:179],as.numeric)
qualtrics[,192:200] <- sapply(qualtrics[,192:200],as.numeric)

# Rename vars
qualtrics <- qualtrics %>% 
  rename(
    age = Q4,
    gender = Q5,
    employment=Q8,
    income = Q10,
    ethnicity=Q12,
    country=Q16,
    lottery.since=Q18,
    lottery.bf=Q64,
    daily.lottery.since=Q19,
    daily.lottery.fb=Q65,
    scratch.since=Q20,
    scratch.bf=Q66,
    raffle.since=Q22,
    raffle.bf=Q67,
    horses.since=Q24,
    horses.bf=Q68,
    bingo.since=Q25,
    bingo.bf=Q69,
    fantasysports.since=Q26,
    fantasysports.bf=Q70,
    casino.themed.app.since=Q27,
    casino.themed.app.bf=Q32,
    online.slots.since=Q35,
    online.slots.bf=Q36,
    internet.since=Q58,
    internet.bf=Q59,
    casino.yes.no=Q29,
    casino.slots= Q30,
    casino.slots.bf=Q33,
    poker.since=Q37,
    poker.bf=Q34,
    roulette.since=Q38,
    roulette.bf=Q39,
    keno.since=Q40,
    keno.bf=Q41,
    craps.since=Q42,
    craps.bf=Q43,
    egm.notslots.since=Q44,
    egm.notslots.bf=Q47,
    sports.lottery.since=Q48,
    sports.lottery.bf=Q49,
    sports.pools.since=Q50,
    sports.pools.bf=Q52,
    card.board.games=Q53,
    card.board.bf=Q54,
    games.of.skills.since=Q55,
    games.of.skills.bf=Q56,
    sports.bet.since=Q60,
    sports.bet.bf=Q61,
    stocks.since=Q62,
    stocks.bf=Q63,
    win.est=Q137,
    pleased=Q82,
    continue.play=Q83,
    game.enjoyable=Q84,
    GEQ3=Q85,
    DQ4=Q86,
    DQ5=Q87,
    GEQ6=Q88,
    DQ7=Q89,
    DQ8=Q90,
    DQ9=Q91,
    id=Random.ID
  )


# Summary gambling experience
#gam_exp.summary <- qualtrics %>% 
#  group_by(experienced,SF) %>% 
#  summarise(mean.lottery=mean(lottery.since,na.rm=TRUE), sd.age=sd(lottery.since,na.rm=TRUE), mean.daily.lottery=mean(daily.lottery.since,na.rm=TRUE),sd.daily.lottery=sd(daily.lottery.since,na.rm=TRUE))

#write.csv(gam_exp.summary,"gam_exp.summary.csv")



# Re-code CPGI
vars <- c(44,46,48,50,52,54,56,58,60,62,65,67,69,71,73,75,77,79,81,83,85,87)
for (i in vars){
  qualtrics[,i] <- ifelse(qualtrics[,i]==1,7,
            ifelse(qualtrics[,i]==2,6,
                   ifelse(qualtrics[,i]==3,5,
                          ifelse(qualtrics[,i]==4,4,
                                 ifelse(qualtrics[,i]==5,3,
                                        ifelse(qualtrics[,i]==6,2,
                                               ifelse(qualtrics[,i]==7,1,0)))))))
}

#PGSI: Q72 - Q80; for PGSI, we are subtracting 1 from the score rather than recoding
qualtrics$pgsi <- as.numeric(qualtrics$Q72)-1+as.numeric(qualtrics$Q73)-1+as.numeric(qualtrics$Q74)-1+as.numeric(qualtrics$Q75)-1+as.numeric(qualtrics$Q76)-1+as.numeric(qualtrics$Q77)-1+as.numeric(qualtrics$Q78)-1+as.numeric(qualtrics$Q79)-1+as.numeric(qualtrics$Q80)-1

# Re-code gambling increase/ decrease
v <- c(51,53,55,57,59,61,63,66,68,70,72,74,76,78,80,82,84,86,88)
for (i in v){
  qualtrics[,i] <- ifelse(qualtrics[,i]==1,"decrease",
                          ifelse(qualtrics[,i]==2,"same","increase"))
}

#Recode employment
qualtrics$employment.recoded <- ifelse(qualtrics$employment==1,"working, paid employee",
                                                   ifelse(qualtrics$employment==2, "working, self-employed",
                                                          ifelse(qualtrics$employment==3,"temporary layoff",
                                                                 ifelse(qualtrics$employment==4,"looking for work",
                                                                        ifelse(qualtrics$employment==5,"not working, retired",
                                                                               ifelse(qualtrics$employment==6,"not working, disabled",
                                                                                      ifelse(qualtrics$employment==7,"not working, other","prefer not to answer")))))))

```

Calculate isolation scores: Social Network Index

```{r}
# create subset with Social Network Index

sni <- qualtrics %>% 
  filter(!is.na(Q144))

# number of high contact roles
# sum of "1,2a,3a,4a,5a,6a,7a,8a,9a,9b,10,11a, 12"

sni$hc.married <- ifelse(sni$Q144<=1,1,0)
sni$hc.married[is.na(sni$hc.married)] = 0

sni$hc.children <- ifelse(sni$Q146>=2,1,0)
sni$hc.children[is.na(sni$hc.children)] = 0

sni$hc.parents <- ifelse(sni$Q148>=2,1,0)
sni$hc.parents[is.na(sni$hc.parents)] = 0

sni$hc.inlaw <- ifelse(sni$Q150>=2,1,0)
sni$hc.inlaw[is.na(sni$hc.inlaw)] = 0

sni$hc.closeR <- ifelse(sni$Q152>=2,1,0)
sni$hc.closeR[is.na(sni$hc.closeR)] = 0

sni$hc.closeF <- ifelse(sni$Q154>=2,1,0)
sni$hc.closeF[is.na(sni$hc.closeF)] = 0

sni$hc.Religion <- ifelse(sni$Q156>=2,1,0)
sni$hc.Religion[is.na(sni$hc.Religion)] = 0

sni$hc.student <- ifelse(sni$Q158>=1,1,0)
sni$hc.student[is.na(sni$hc.student)] = 0

sni$hc.peoplework <- ifelse(sni$Q161>=2,1,0)
sni$hc.peoplework[is.na(sni$hc.peoplework)] = 0

sni$hc.supervises <- ifelse(sni$Q160>=2,1,0)
sni$hc.supervises[is.na(sni$hc.supervises)] = 0

sni$hc.neighbor <- ifelse(sni$Q162>=2,1,0)
sni$hc.neighbor[is.na(sni$hc.neighbor)] = 0

sni$hc.volunteer <- ifelse(sni$Q164>=2,1,0)
sni$hc.volunteer[is.na(sni$hc.volunteer)] = 0

sni$hc.groupM <- ifelse(sni$Q165>=2,1,0)
sni$hc.groupM[is.na(sni$hc.groupM)] = 0

#High contact score (221)
sni$hi.contact.roles <- rowSums(sni[ , c(208,209,210,211,212,213,214,215,216,217,218,219,220)], na.rm=TRUE) 

# number of people in social network

# sum of 1, 2a num.,3a 1,2=1 3=2,4a 1,2=1 3=2 ,5a num.,6 num.,7a nu.m, 8a num., 9a/9b sum, 10 num., 11a num., 12 num.

sni$sn.married <- ifelse(sni$Q144<=1,1,0)
sni$sn.married[is.na(sni$sn.married)] = 0

sni$sn.children <- sni$Q146-1
sni$sn.children[is.na(sni$sn.children)] = 0

sni$sn.parents <- ifelse(sni$Q148<=3,1,2)
sni$sn.parents[is.na(sni$sn.parents)] = 0

sni$sn.inlaw <- ifelse(sni$Q150<=3,1,2)
sni$sn.inlaw[is.na(sni$sn.inlaw)] = 0

sni$sn.closer <- sni$Q152-1
sni$sn.closer[is.na(sni$sn.closer)] = 0

sni$sn.closef <- sni$Q154-1
sni$sn.closef[is.na(sni$sn.closef)] = 0

sni$sn.religion <- sni$Q156-1
sni$sn.religion[is.na(sni$sn.religion)] = 0

sni$sn.student <- sni$Q146-1
sni$sn.student[is.na(sni$sn.student)] = 0


sni$sn.supervises <- sni$Q160-1
sni$sn.supervises[is.na(sni$sn.supervises)] = 0

sni$sn.peoplework <- sni$Q161-1
sni$sn.peoplework[is.na(sni$sn.peoplework)] = 0

sni$sn.work <- rowSums(sni[ , c(230,231)], na.rm=TRUE) 

sni$sn.neighbor <- sni$Q162-1
sni$sn.neighbor[is.na(sni$sn.neighbor)] = 0

sni$sn.volunteer <- sni$Q164-1
sni$sn.volunteer[is.na(sni$sn.volunteer)] = 0

is.character(sni$Q167_2)&&length(sni$Q167_2)==1
is.numeric(sni$Q167_2)

# Correcting fill-in the blanks
sni$Q167_2.2 <-as.numeric(sni$Q167_2)
sni$Q167_2.2[is.na(sni$Q167_2.2)] = 0

sni$Q167_7.7 <-as.numeric(sni$Q167_7)
sni$Q167_7.7[is.na(sni$Q167_7.7)] = 0

sni$Q167_8.8 <-as.numeric(sni$Q167_8)
sni$Q167_8.8[is.na(sni$Q167_8.8)] = 0


sni$Q167_9.9 <-as.numeric(sni$Q167_9)
sni$Q167_9.9[is.na(sni$Q167_9.9)] = 0

sni$Q167_10.1 <-as.numeric(sni$Q167_10)
sni$Q167_10.1[is.na(sni$Q167_10.1)] = 0

sni$Q167_11.1 <-as.numeric(sni$Q167_11)
sni$Q167_11.1[is.na(sni$Q167_11.1)] = 0

sni$sn.groupm  <- rowSums(sni[ , c(235,236,237,238,239,240)], na.rm=TRUE) 

# Social network score (241)
sni$sn.score  <- rowSums(sni[ , c(222,223,224,225,226,227,228,229,230,231,232,233,234,241)], na.rm=TRUE) 


#  of Embedded Network Scores

#en.married=sn.married cloumn (222)
#en.children=sn.children column (223)

sni$en.parents <- sni$Q148-1
sni$en.parents[is.na(sni$en.parents)] = 0

sni$en.inlaw <- sni$Q150-1
sni$en.inlaw[is.na(sni$en.inlaw)] = 0

sni$en.closer <- sni$Q152-1
sni$en.closer[is.na(sni$en.closer)] = 0

sni$en.family  <- rowSums(sni[ , c(222,223,242,243,244)], na.rm=TRUE)
sni$en.Vfamily <- ifelse(sni$en.family>=7,1,0)

sni$en.closef <-ifelse(sni$sn.closef>=4,1,0)

sni$en.religion <-ifelse(sni$sn.religion>=4,1,0)

sni$en.student <-ifelse(sni$sn.student>=4,1,0)

sni$en.work <-ifelse(sni$sn.work>=4,1,0)

sni$en.neighbor <-ifelse(sni$sn.neighbor>=4,1,0)

sni$en.volunteer <-ifelse(sni$sn.volunteer>=4,1,0)

sni$en.groupm <-ifelse(sni$sn.groupm>=4,1,0)

#Embedded Network Score (255)
sni$en.score  <- rowSums(sni[ , c(247,248,249,250,251,252,253,254)], na.rm=TRUE) 

```

Associations between social isolation

```{r}

ml <- multinom(lottery.bf ~ lottery.since + pgsi + employment+en.score, data=sni)
summary(ml)
confint(ml)
MASS::dropterm(ml, trace=FALSE, test="Chisq")


````

